package me.isassist.isa;

public enum Mode {
    LIST_CITY_OFFICES,
    LIST_CASH_MACHINES,
    LIST_DORMITORIES,
    LIST_PHARMACIES,
    LIST_HOTELS,
    LIST_POLICE_OFFICES,
    LIST_SPORT_FIELDS,
    LIST_SWIMMING_POOLS,
    LIST_VETURILO,
    LIST_THEATRES,
    LOADING_FROM_FILES,
    UPDATING,
    MAIN_FRAGMENT;
}
